version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    #environment:
      #- MONGODB_USERNAME=yaniv
      #MONGODB_USERNAME: yaniv
      #MONGODB_PASSWORD: ybd ybd
    env_file:
        - ./env/mongo.env
  backend:  
    build: ./backend
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
        - ./env/backend.env
    ports:
      - 80:80
    depends_on:
      - mongodb
 # frontend:
volumes:
  data:
  logs: