version: "3.8"
services:
  mongodb:
    image: "mongo"
    volumes:
      - data:/data/db
    #environment:
      #- MONGODB_USERNAME=yaniv
      #MONGODB_USERNAME: yaniv
      #MONGODB_PASSWORD: ybd ybd
    env_file:
        - ./env/mongo.env
  backend:  
    build: ./backend
    volumes:
      - ./backend/logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
        - ./env/backend.env
    ports:
      - 80:80
    depends_on:
      - mongodb
  frontend:
    build: ./frontend
    volumes:
      - ./frontend/src:/app/src
    ports:
      - 3000:3000
    depends_on:
      - backend
    stdin_open: true
    tty: true
volumes:
  data: